<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EstateFlow.Application\EstateFlow.Application.csproj" />
    <ProjectReference Include="..\EstateFlow.Infrastructure\EstateFlow.Infrastructure.csproj" />
  </ItemGroup>
</Project>
